# Command: bundle exec jazzy

readme: ../README.md
author: Nimble
author_url: https://github.com/nimblehq/local-authentication-ios
clean: true
sdk: iphonesimulator
podspec: ../NimbleLocalAuthentication.podspec
min_acl: public
pod_sources: ["https://cdn.cocoapods.org"]
