name: Tests

on:
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Install RubyGems
      run: gem install bundler
      working-directory: ./Example
    - name: Bundle install
      run: bundle install
      working-directory: ./Example
    - name: Install Cocoapods
      run: bundle exec pod install --repo-update
      working-directory: ./Example
    - name: Test
      env: 
        CI: true
      run: bundle exec fastlane tests
      working-directory: ./Example
